import type { Question } from "../session/sessionTypes";

export const QUESTION_SET_VERSION = 1;

export const questions: Question[] = [
  {
    id: "q01",
    domain: "relationship_energy",
    facet: "date_rhythm",
    textKey: "question.relationship_energy.q01",
    reverseScored: false,
    resultTags: ["contact_frequency", "stability_by_connection"],
    version: QUESTION_SET_VERSION,
  },
  {
    id: "q02",
    domain: "relationship_energy",
    facet: "planning_comfort",
    textKey: "question.relationship_energy.q02",
    reverseScored: false,
    resultTags: ["planning_style", "predictability"],
    version: QUESTION_SET_VERSION,
  },
  {
    id: "q03",
    domain: "relationship_energy",
    facet: "novelty_preference",
    textKey: "question.relationship_energy.q03",
    reverseScored: false,
    resultTags: ["novelty_energy", "activity"],
    version: QUESTION_SET_VERSION,
  },
  {
    id: "q04",
    domain: "relationship_energy",
    facet: "quiet_togetherness",
    textKey: "question.relationship_energy.q04",
    reverseScored: false,
    resultTags: ["quiet_togetherness", "calm_bond"],
    version: QUESTION_SET_VERSION,
  },
  {
    id: "q05",
    domain: "relationship_energy",
    facet: "social_energy",
    textKey: "question.relationship_energy.q05",
    reverseScored: false,
    resultTags: ["social_energy", "outside_stimulation"],
    version: QUESTION_SET_VERSION,
  },
  {
    id: "q06",
    domain: "relationship_energy",
    facet: "routine_care",
    textKey: "question.relationship_energy.q06",
    reverseScored: false,
    resultTags: ["routine_care", "consistency"],
    version: QUESTION_SET_VERSION,
  },
  {
    id: "q07",
    domain: "closeness_style",
    facet: "reassurance_need",
    textKey: "question.closeness_style.q07",
    reverseScored: false,
    resultTags: ["reassurance_sensitivity", "verbal_confirmation"],
    version: QUESTION_SET_VERSION,
  },
  {
    id: "q08",
    domain: "closeness_style",
    facet: "distance_sensitivity",
    textKey: "question.closeness_style.q08",
    reverseScored: false,
    resultTags: ["reassurance_sensitivity", "distance_sensitivity"],
    version: QUESTION_SET_VERSION,
  },
  {
    id: "q09",
    domain: "closeness_style",
    facet: "personal_space",
    textKey: "question.closeness_style.q09",
    reverseScored: false,
    resultTags: ["personal_space_independence", "boundary"],
    version: QUESTION_SET_VERSION,
  },
  {
    id: "q10",
    domain: "closeness_style",
    facet: "closeness_pace",
    textKey: "question.closeness_style.q10",
    reverseScored: false,
    resultTags: ["sharing_pace", "emotional_sharing"],
    version: QUESTION_SET_VERSION,
  },
  {
    id: "q11",
    domain: "closeness_style",
    facet: "independence_comfort",
    textKey: "question.closeness_style.q11",
    reverseScored: false,
    resultTags: ["personal_space_independence", "autonomy"],
    version: QUESTION_SET_VERSION,
  },
  {
    id: "q12",
    domain: "closeness_style",
    facet: "direct_check",
    textKey: "question.closeness_style.q12",
    reverseScored: false,
    resultTags: ["direct_check_style", "clarity"],
    version: QUESTION_SET_VERSION,
  },
  {
    id: "q13",
    domain: "affection_expression",
    facet: "words_affection",
    textKey: "question.affection_expression.q13",
    reverseScored: false,
    resultTags: ["words_affection", "verbal_affection"],
    version: QUESTION_SET_VERSION,
  },
  {
    id: "q14",
    domain: "affection_expression",
    facet: "focused_time",
    textKey: "question.affection_expression.q14",
    reverseScored: false,
    resultTags: ["focused_time", "attention"],
    version: QUESTION_SET_VERSION,
  },
  {
    id: "q15",
    domain: "affection_expression",
    facet: "practical_care",
    textKey: "question.affection_expression.q15",
    reverseScored: false,
    resultTags: ["practical_care", "acts_of_care"],
    version: QUESTION_SET_VERSION,
  },
  {
    id: "q16",
    domain: "affection_expression",
    facet: "physical_closeness",
    textKey: "question.affection_expression.q16",
    reverseScored: false,
    resultTags: ["physical_closeness", "warmth"],
    version: QUESTION_SET_VERSION,
  },
  {
    id: "q17",
    domain: "affection_expression",
    facet: "small_ritual",
    textKey: "question.affection_expression.q17",
    reverseScored: false,
    resultTags: ["symbolic_ritual", "memory"],
    version: QUESTION_SET_VERSION,
  },
  {
    id: "q18",
    domain: "affection_expression",
    facet: "memory_detail",
    textKey: "question.affection_expression.q18",
    reverseScored: false,
    resultTags: ["detail_memory", "attentiveness"],
    version: QUESTION_SET_VERSION,
  },
  {
    id: "q19",
    domain: "conflict_recovery",
    facet: "immediate_talk",
    textKey: "question.conflict_recovery.q19",
    reverseScored: false,
    resultTags: ["conflict_timing", "immediate_talk"],
    version: QUESTION_SET_VERSION,
  },
  {
    id: "q20",
    domain: "conflict_recovery",
    facet: "cooling_time",
    textKey: "question.conflict_recovery.q20",
    reverseScored: false,
    resultTags: ["conflict_timing", "cooling_time"],
    version: QUESTION_SET_VERSION,
  },
  {
    id: "q21",
    domain: "conflict_recovery",
    facet: "empathy_first",
    textKey: "question.conflict_recovery.q21",
    reverseScored: false,
    resultTags: ["empathy_solution_balance", "empathy_first"],
    version: QUESTION_SET_VERSION,
  },
  {
    id: "q22",
    domain: "conflict_recovery",
    facet: "solution_first",
    textKey: "question.conflict_recovery.q22",
    reverseScored: false,
    resultTags: ["empathy_solution_balance", "solution_first"],
    version: QUESTION_SET_VERSION,
  },
  {
    id: "q23",
    domain: "conflict_recovery",
    facet: "apology_repair",
    textKey: "question.conflict_recovery.q23",
    reverseScored: false,
    resultTags: ["repair_action", "behavior_change"],
    version: QUESTION_SET_VERSION,
  },
  {
    id: "q24",
    domain: "conflict_recovery",
    facet: "revisit_after_calm",
    textKey: "question.conflict_recovery.q24",
    reverseScored: false,
    resultTags: ["revisit_after_calm", "follow_up"],
    version: QUESTION_SET_VERSION,
  },
  {
    id: "q25",
    domain: "adjustment_anchor",
    facet: "adjustment_readiness",
    textKey: "question.adjustment_anchor.q25",
    reverseScored: false,
    resultTags: ["adjustment_readiness", "report_tone"],
    version: QUESTION_SET_VERSION,
  },
];
